-- Nuvora next-step migration for an already-running Nuvora/Little Films database.
-- Run this after the earlier Nuvora migration to enable image uploads + analytics.

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public=true;

drop policy if exists "nuvora product images admin insert" on storage.objects;
create policy "nuvora product images admin insert" on storage.objects for insert to authenticated
with check (
  bucket_id='product-images'
  and exists (select 1 from public.profiles p where p.id=auth.uid() and (p.is_admin=true or coalesce(p.role,'')='admin'))
);

drop policy if exists "nuvora product images admin update" on storage.objects;
create policy "nuvora product images admin update" on storage.objects for update to authenticated
using (
  bucket_id='product-images'
  and exists (select 1 from public.profiles p where p.id=auth.uid() and (p.is_admin=true or coalesce(p.role,'')='admin'))
)
with check (
  bucket_id='product-images'
  and exists (select 1 from public.profiles p where p.id=auth.uid() and (p.is_admin=true or coalesce(p.role,'')='admin'))
);

drop policy if exists "nuvora product images admin delete" on storage.objects;
create policy "nuvora product images admin delete" on storage.objects for delete to authenticated
using (
  bucket_id='product-images'
  and exists (select 1 from public.profiles p where p.id=auth.uid() and (p.is_admin=true or coalesce(p.role,'')='admin'))
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  product_id uuid references public.products(id) on delete set null,
  session_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.analytics_events enable row level security;
drop policy if exists "public analytics event insert" on public.analytics_events;
create policy "public analytics event insert" on public.analytics_events
for insert to anon, authenticated
with check (char_length(event_name) between 1 and 80);
